# Generated by Django 3.2 on 2021-04-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_occupation', models.CharField(max_length=100)),
                ('client_DOB', models.DateTimeField(verbose_name='date of birth')),
                ('client_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('client_address', models.CharField(max_length=200)),
            ],
        ),
    ]
