# Generated by Django 3.2 on 2021-04-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_DOB',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_gender',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_occupation',
        ),
        migrations.AddField(
            model_name='client',
            name='client_contact',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
