# Generated by Django 3.2 on 2021-04-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_post', models.CharField(max_length=100)),
                ('emp_DOB', models.DateTimeField(verbose_name='date of birth')),
                ('emp_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_salary', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateTimeField(verbose_name='receive date')),
                ('completion_date', models.DateTimeField(verbose_name='completion date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('emp_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.employee')),
            ],
        ),
    ]
