# Generated by Django 3.2 on 2021-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='freelancer',
            fields=[
                ('ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('DOB', models.DateTimeField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('payment', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
