# Generated by Django 3.2 on 2021-04-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20210426_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='clean_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', models.DateTimeField(verbose_name='receive date')),
                ('completion_date', models.DateTimeField(null=True, verbose_name='completion date')),
                ('address', models.CharField(max_length=200)),
                ('emp_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='request',
        ),
    ]
